# Generated by Django 5.0.14 on 2026-07-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InspectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_name", models.CharField(max_length=100)),
                ("product_model", models.CharField(max_length=100)),
                (
                    "test_condition",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Oil", "Oil"),
                            ("Light", "Light"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_production", models.IntegerField()),
                ("machine_ng", models.IntegerField(default=0)),
                ("machine_ok", models.IntegerField(default=0)),
                ("pqc_ng", models.IntegerField(default=0)),
                ("pqc_ok", models.IntegerField(default=0)),
                ("defect_list", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
