# Generated by Django 5.0.14 on 2026-07-01 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspectionrecord",
            options={
                "ordering": ["-inspection_date", "-inspection_time", "-created_at"]
            },
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="bush_vertical_defect_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="bush_vertical_misaligned_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="forgotten_bush_vertical_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="inspection_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="inspection_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="kanban_mismatch_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="not_enter_bush_vertical_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="round_recline_leak_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="spatter_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="stopper_leak_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="line_name",
            field=models.CharField(
                choices=[
                    ("Line 1", "Line 1"),
                    ("Line 2", "Line 2"),
                    ("Line 3", "Line 3"),
                    ("Line 4", "Line 4"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="machine_ng",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="machine_ok",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="pqc_ng",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="pqc_ok",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="total_production",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
