# Generated by Django 5.0.14 on 2026-07-01 07:22

import django.db.models.deletion
from django.db import migrations, models


def populate_master_data(apps, schema_editor):
    InspectionRecord = apps.get_model("inspection", "InspectionRecord")
    ProductionLine = apps.get_model("inspection", "ProductionLine")
    ProductModel = apps.get_model("inspection", "ProductModel")
    TestCondition = apps.get_model("inspection", "TestCondition")

    for record in InspectionRecord.objects.all():
        line_name = getattr(record, "line_name_old", None)
        if line_name:
            line, _ = ProductionLine.objects.get_or_create(name=str(line_name))
            record.line_id = line.pk

        product_model_name = getattr(record, "product_model_old", None)
        if product_model_name:
            product_model, _ = ProductModel.objects.get_or_create(name=str(product_model_name))
            record.product_model_id = product_model.pk

        test_condition_name = getattr(record, "test_condition_old", None)
        if test_condition_name:
            test_condition, _ = TestCondition.objects.get_or_create(name=str(test_condition_name))
            record.test_condition_id = test_condition.pk

        record.save(update_fields=["line_id", "product_model_id", "test_condition_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0002_alter_inspectionrecord_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="inspectionrecord",
            old_name="line_name",
            new_name="line_name_old",
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.productionline",
            ),
        ),
        migrations.RenameField(
            model_name="inspectionrecord",
            old_name="product_model",
            new_name="product_model_old",
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="product_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.productmodel",
            ),
        ),
        migrations.RenameField(
            model_name="inspectionrecord",
            old_name="test_condition",
            new_name="test_condition_old",
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="test_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.testcondition",
            ),
        ),
        migrations.RunPython(populate_master_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="line",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.productionline",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="product_model",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.productmodel",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="test_condition",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.testcondition",
            ),
        ),
        migrations.RemoveField(
            model_name="inspectionrecord",
            name="line_name_old",
        ),
        migrations.RemoveField(
            model_name="inspectionrecord",
            name="product_model_old",
        ),
        migrations.RemoveField(
            model_name="inspectionrecord",
            name="test_condition_old",
        ),
    ]
