# Generated by Django 5.0.14 on 2026-07-01 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inspection",
            "0003_defecttype_productionline_productmodel_testcondition_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionrecord",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.productionline",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="product_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.productmodel",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="test_condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_records",
                to="inspection.testcondition",
            ),
        ),
    ]
