# Generated by Django 5.0.14 on 2026-07-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0004_alter_inspectionrecord_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defecttype",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="inspectionrecord",
            name="inspection_date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="testcondition",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="inspectionrecord",
            index=models.Index(
                fields=["inspection_date", "line"], name="insp_date_line_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrecord",
            index=models.Index(
                fields=["line", "inspection_date", "inspection_time"],
                name="insp_line_date_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrecord",
            index=models.Index(
                fields=["product_model", "inspection_date"], name="insp_model_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrecord",
            index=models.Index(
                fields=["test_condition", "inspection_date"], name="insp_cond_date_idx"
            ),
        ),
    ]
