# Generated by Django 5.0.14 on 2026-07-02 04:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0006_inspectiondefect_normalized"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("found", "ตรวจเจอ"),
                            ("not_found", "ตรวจไม่เจอ"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("round_no", models.PositiveIntegerField(default=1)),
                ("found_count", models.PositiveIntegerField(default=0)),
                ("not_found_count", models.PositiveIntegerField(default=0)),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-inspection_date", "-round_no", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inspectiondefect",
            name="machine_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectiondefect",
            name="pqc_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="initial_control",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="part_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="result",
            field=models.CharField(
                choices=[("ok", "OK"), ("ng", "NG"), ("pending", "Pending")],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="sd_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="inspectionrecord",
            name="verify",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="inspectionrecord",
            index=models.Index(
                fields=["sd_code", "inspection_date"], name="insp_sd_code_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionrecord",
            index=models.Index(
                fields=["result", "inspection_date"], name="insp_result_date_idx"
            ),
        ),
        migrations.AddField(
            model_name="verificationrecord",
            name="defect_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_records",
                to="inspection.defecttype",
            ),
        ),
        migrations.AddField(
            model_name="verificationrecord",
            name="test_condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_records",
                to="inspection.testcondition",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrecord",
            index=models.Index(
                fields=["inspection_date", "defect_type"], name="verify_date_defect_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrecord",
            index=models.Index(
                fields=["test_condition", "inspection_date"],
                name="verify_cond_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrecord",
            index=models.Index(
                fields=["result", "inspection_date"], name="verify_result_date_idx"
            ),
        ),
    ]
