# Generated by Django 5.0.14 on 2026-07-02 07:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inspection",
            "0007_verificationrecord_inspectiondefect_machine_quantity_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionResultType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inspector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InspectionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "inspection_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
                ("overall_comment", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_sessions",
                        to="inspection.productionline",
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_sessions",
                        to="inspection.productmodel",
                    ),
                ),
                (
                    "test_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_sessions",
                        to="inspection.testcondition",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_sessions",
                        to="inspection.inspector",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(blank=True, default="", max_length=150)),
                ("total_rounds", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "defect_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_tests",
                        to="inspection.defecttype",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="inspection.inspectionsession",
                    ),
                ),
            ],
            options={
                "ordering": ["defect_type__name", "test_name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_rounds",
                        to="inspection.inspectionresulttype",
                    ),
                ),
                (
                    "inspection_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="inspection.inspectiontest",
                    ),
                ),
            ],
            options={
                "ordering": ["inspection_test", "round_number"],
            },
        ),
        migrations.AddIndex(
            model_name="inspectiontest",
            index=models.Index(
                fields=["session", "defect_type"], name="test_session_defect_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectiontest",
            index=models.Index(fields=["defect_type"], name="test_defect_idx"),
        ),
        migrations.AddConstraint(
            model_name="inspectiontest",
            constraint=models.UniqueConstraint(
                fields=("session", "defect_type"), name="uniq_session_defect_test"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionround",
            index=models.Index(
                fields=["inspection_test", "round_number"], name="round_test_number_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionround",
            index=models.Index(fields=["result_type"], name="round_result_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="inspectionround",
            constraint=models.UniqueConstraint(
                fields=("inspection_test", "round_number"),
                name="uniq_test_round_number",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionsession",
            index=models.Index(
                fields=["inspection_date", "line"], name="session_date_line_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionsession",
            index=models.Index(
                fields=["product_model", "inspection_date"],
                name="session_model_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionsession",
            index=models.Index(
                fields=["test_condition", "inspection_date"],
                name="session_cond_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionsession",
            index=models.Index(
                fields=["inspector", "inspection_date"], name="session_insp_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionsession",
            index=models.Index(
                fields=["status", "inspection_date"], name="session_status_date_idx"
            ),
        ),
    ]
